class OrderAddress {
  bool addressValidate;
  //...
  String address;
  String latitude;
  String longitude;
  //...
  String state;
  String district;
  String subDistrict;
  String postalCode;

  OrderAddress({
    required this.addressValidate,
    required this.address,
    required this.latitude,
    required this.longitude,
    required this.state,
    required this.district,
    required this.subDistrict,
    required this.postalCode,
  });
}

Map<String, Map<String, List<String>>> addressState = {
  'WP Kuala Lumpur': {
    'Batu': [
      'Batu Kentonmen',
      'Bdr Baru Sentul',
      'Kaw Ind IKS',
      'Kaw Ind Spring Crest',
      'Kg Batu',
      'Kg Batu Delima',
      'Kg Batu Muda',
      'Kg Chubadak',
      'Kg Sri Batu',
      'Pusat Bdr Utara Selayang',
      'Selayang',
      'Sentul',
      'Sentul Jaya',
      'Sentul Pasar',
      'Sentul Selatan',
      'Sentul Utara',
      'Setapak',
      'Titiwangsa Sentral',
      'Tmn Aman Putra',
      'Tmn Batu Muda',
      'Tmn Batu Permai',
      'Tmn Batu View',
      'Tmn Beringin',
      'Tmn Bullion Mewah',
      'Tmn Dato Senu',
      'Tmn Desa Bakti',
      'Tmn Eastern',
      'Tmn Impian',
      'Tmn Intan Baiduri',
      'Tmn Kaya',
      'Tmn Kok Lian',
      'Tmn Koperasi',
      'Tmn Koperasi 2',
      'Tmn Kosmo Jaya',
      'Tmn Mastiara',
      'Tmn Million',
      'Tmn Nanyang',
      'Tmn Rainbow',
      'Tmn Selayang Baru',
      'Tmn Selayang Indah',
      'Tmn Sentul Bahagia',
      'Tmn Setapak Indah Jaya',
      'Tmn Sri Murni',
      'Tmn Tasik Indah',
      'Tmn Wahyu',
      'Tmn Wilayah',
    ],
    'Bdr Tun Razak': [
      'Bdr Sri Permaisuri',
      'Bdr Tasik Selatan',
      'Bdr Tun Razak',
      'Desa Tun Razak',
      'Kg Malaysia Raya',
      'Perumahan Awam',
      'Sg Besi',
      'Tmn Alam Damai',
      'Tmn Bkt Anggerik',
      'Tmn Bkt Cheras',
      'Tmn Damai Budi',
      'Tmn Damai Kasih',
      'Tmn Damai Murni',
      'Tmn Damai Rasa',
      'Tmn Desa Cheras',
      'Tmn Ikan Emas',
      'Tmn Len Seng',
      'Tmn Mulia',
      'Tmn Orkid Desa',
      'Tmn Orkid Desa 2',
      'Tmn Tasik Damai',
      'Tmn Tasik Permaisuri',
    ],
    'Bkt Bintang': [
      '(Old) City Centre',
      'Bkt Bintang',
      'Bkt Nanas',
      'Bkt Petaling',
      'Bkt Weld',
      'Brickfields',
      'Chan Sow Lin',
      'Chow Kit',
      'Desa Petaling',
      'Imbi',
      'Kg Attap',
      'KL Sentral',
      'KLCC',
      'Medan Pasar',
      'Medan Tuanku',
      'Mid Valley',
      'Pudu',
      'Salak Selatan',
      'Seputeh',
      'Tmn Bkt Seputeh',
      'Tmn Desa Seputeh',
      'Tmn Mutiara Seputeh',
      'Tmn Seputeh',
    ],
    'Cheras': [
      'Chan Sow Lin',
      'Cheras',
      'Kg Cheras Baru',
      'Perumahan Awam',
      'Pudu',
      'Tmn Bahagia',
      'Tmn Bkt Hijau',
      'Tmn Bkt Permai',
      'Tmn Bkt Ria',
      'Tmn Bkt Segar',
      'Tmn Bkt Segar Jaya',
      'Tmn Cheras',
      'Tmn Cheras Hartamas',
      'Tmn Cheras Utama',
      'Tmn Connaught',
      'Tmn Desa Aman',
      'Tmn Gemilang',
      'Tmn Kobena',
      'Tmn Midah',
      'Tmn Miharja',
      'Tmn Mutiara',
      'Tmn Pertama',
      'Tmn Pudu Hulu',
      'Tmn Rakyat',
      'Tmn Segar',
      'Tmn Shamelin Perkasa',
      'Tmn Sri Bahtera',
      'Tmn Supreme',
      'Tmn Taynton View',
    ],
    'Kepong': [
      'Jinjang',
      'Jinjang Selatan',
      'Jinjang Selatan Tambahan',
      'Jinjang Utara',
      'Jinjang Utara Tambahan',
      'Kaw Ind Kepong Baru',
      'Kaw Ind Ringan Seri Endaran',
      'Kaw Ind TSI',
      'Kaw Ush Kepong',
      'Kepong',
      'Kepong Baru',
      'Kepong Baru Tambahan',
      'Kepong Entr Park',
      'Kepong Metro Prima',
      'Kg Bangkong',
      'Kg Melayu Kepong',
      'Laman Rimbunan',
      'Perumahan Awam',
      'Tmn Cuepacs',
      'Tmn Fadason',
      'Tmn Jinjang Baru',
      'Tmn Kepong',
      'Tmn Kepong Indah',
      'Tmn Kom MWE',
      'Tmn Megah',
      'Tmn Megah Kepong',
      'Tmn Metropolitan Kepong',
      'Tmn Petaling',
      'Tmn Pusat Kepong',
      'Tmn Segambut Aman',
      'Tmn Seri Kepong Baru',
      'Tmn Usahawan',
    ],
    'Lembah Pantai': [
      'Bangsar',
      'Bangsar Baru',
      'Bangsar South',
      'Bkt Bandaraya',
      'Bkt Bangsar',
      'Bkt Kerinchi',
      'Bkt Pantai',
      'Bkt Persekutuan',
      'Bkt Putra',
      'Gasing Indah',
      'Kg Hj Abdullah Hukum',
      'Kg Kerinchi',
      'Kg Pantai',
      'Kg Pasir',
      'Kg Pasir Baru',
      'Pantai Dalam',
      'Pantai Hill Park',
      'Perumahan Awam',
      'Pusat Bdr Damansara',
      'Tasik Perdana',
      'Tmn Bandaraya',
      'Tmn Bkt Angkasa',
      'Tmn Bkt Pantai',
      'Tmn Dato',
      'Tmn Desa Kerinchi',
      'Tmn Lucky',
      'Tmn Nam Fong',
      'Tmn Pantai Indah',
      'Tmn SA',
      'Tmn Sri Sentosa',
    ],
    'Segambut': [
      '3rd Mile Jln Ipoh',
      'Bdr Menjalara',
      'Bkt Damansara',
      'Bkt Kiara',
      'Bkt Prima Pelangi',
      'Bkt Segambut',
      'Bkt Tunku',
      'Country Heights Damansara',
      'Damansara Heights',
      'Desa Park City',
      'Desa Sri Hartamas',
      'Dutamas',
      'Kaw Ind Segambut',
      'Kaw Ush Tmn Bkt Maluri',
      'Kg Benting Segambut',
      'Kg Bkt Lanjan',
      'Kg Kasipillay',
      'Kg Melayu Segambut',
      'Kg Palimbayan Indah',
      'Kg Pasir Segambut',
      'Kg Segambut Dalam',
      'Kg Segambut Tengah',
      'Kg Sg Penchala',
      'Kg Sg Udang',
      'Komp Kerajaan',
      'Medan Damansara',
      'Mont Kiara',
      'Segambut',
      'Sri Hartamas',
      'Sunway SPK Damansara',
      'Tmn Bamboo',
      'Tmn Batu',
      'Tmn Bkt Damansara',
      'Tmn Bkt Maluri',
      'Tmn City',
      'Tmn Damansara Endah',
      'Tmn Desa Segambut',
      'Tmn Duta',
      'Tmn Goh Nam Huat',
      'Tmn Golden',
      'Tmn Kok Doh',
      'Tmn Lawa',
      'Tmn Niaga Waris',
      'Tmn Pinggir Tun Dr Ismail',
      'Tmn Prima Impian',
      'Tmn Segambut',
      'Tmn Segambut Bahagia',
      'Tmn Segambut Bahagia Tambahan',
      'Tmn Segambut Damai',
      'Tmn Segambut Indah',
      'Tmn Segambut Jaya',
      'Tmn Segambut Muda',
      'Tmn Segambut SPPK',
      'Tmn Segambut Tambahan',
      'Tmn Sejahtera',
      'Tmn Sri Bintang',
      'Tmn Sri Bkt Segambut',
      'Tmn Sri Kuching',
      'Tmn Sri Segambut',
      'Tmn Sri Sinar',
      'Tmn Teh Wan Sang',
      'Tmn Tun Dr Ismail',
    ],
    'Seputeh': [
      '3rd Mile Jln Klang Lama',
      'Bdr Baru Sri Petaling',
      'Bkt Jalil',
      'Bkt OUG',
      'Kaw Ind OUG',
      'Kg Bohol Baru',
      'Kg Muhibbah',
      'Klang Lama',
      'Kuchai Entr Park',
      'Kuchai Lama',
      'Mutiara Bkt Jalil',
      'Petaling Lama',
      'PPR Kg Muhibbah',
      'Puchong',
      'Seputeh',
      'Sg Besi',
      'Teknologi Park Malaysia',
      'Tmn Abadi Indah',
      'Tmn Angkasa',
      'Tmn Angsona',
      'Tmn Bkt Aman',
      'Tmn Bkt Desa',
      'Tmn Bkt Indah',
      'Tmn Castlefield',
      'Tmn Continental',
      'Tmn Danau Desa',
      'Tmn Desa',
      'Tmn Esplanad',
      'Tmn Gembira',
      'Tmn Goodwood',
      'Tmn Halimahton',
      'Tmn Hock Ann',
      'Tmn Impian Indah',
      'Tmn Kuchai Jaya',
      'Tmn Lian Hoe',
      'Tmn Lucky',
      'Tmn Naga Emas',
      'Tmn OUG',
      'Tmn Pagar Ruyong',
      'Tmn Parklane OUG',
      'Tmn Pasir Permata',
      'Tmn Puchong Indah',
      'Tmn Salak Selatan',
      'Tmn Serangkai',
      'Tmn Shanghai',
      'Tmn Skyline',
      'Tmn Sri Endah',
      'Tmn Sri Jati',
      'Tmn Sri Pandyan',
      'Tmn Tan Yew Lai',
      'Tmn United',
      'Tmn Yarl',
    ],
    'Setiawangsa': [
      'Desa Tun Hussein Onn',
      'Genting Klang',
      'Gurney',
      'Kaw Ind Setapak',
      'Kementah',
      'Kg Baru Air Panas',
      'Kg Semarak',
      'Padang Tembak',
      'Perumahan Awam',
      'Rampai Business Park',
      'Setapak',
      'Tmn Ayer Panas',
      'Tmn Danau Kota',
      'Tmn Desa Keramat',
      'Tmn Keramat',
      'Tmn Megan Setapak',
      'Tmn Setapak Jaya',
      'Tmn Setapak Permai',
      'Tmn Setiawangsa',
      'Tmn Sri Keramat',
      'Tmn Sri Rampai',
      'Tmn Tasik Titiwangsa',
      'Wangsa Maju',
    ],
    'Titiwangsa': [
      'Ampang',
      'Ampang Hilir',
      'Cochrane',
      'Desa Pandan',
      'Kaw Ind Pandan Indah',
      'Kg Baru',
      'Kg Baru Ampang Tambahan',
      'Kg Datuk Keramat',
      'Kg Pandan',
      'Pandan Cahaya',
      'Pandan Indah',
      'Pandan Jaya',
      'Pandan Mewah',
      'Pandan Perdana',
      'Pudu',
      'Raja Muda',
      'Setapak',
      'Tmn Bkt Pandan',
      'Tmn Bkt Teratai',
      'Tmn Cheras Indah',
      'Tmn Kencana',
      'Tmn Kom Pandan Indah',
      'Tmn Lembah Maju',
      'Tmn Maju jaya',
      'Tmn Maluri',
      'Tmn Mastika',
      'Tmn Mawar',
      'Tmn Mega Jaya',
      'Tmn Muda',
      'Tmn Putra',
      'Tmn Seraya',
      'Tmn U-Thant',
    ],
    'Wangsa Maju': [
      'Genting Klang',
      'Gombak',
      'Kg Bdr Dalam',
      'Kg Kuantan',
      'Kg Padang Balang',
      'Kg Puah',
      'Kg Sg Merali',
      'Kg Sg Mulia',
      'Setapak',
      'Tmn Bunga Raya',
      'Tmn Danau Kota',
      'Tmn Desa Andaman',
      'Tmn Desa Melawati',
      'Tmn Desa Setapak',
      'Tmn Ibu Kota',
      'Tmn Medan Idaman',
      'Tmn Melati',
      'Tmn P.Ramlee',
      'Tmn Pelangi Jaya',
      'Tmn Seri Melati',
      'Tmn Setapak',
      'Tmn Setapak Indah',
      'Tmn Suria Setapak',
      'Tmn Tai Onn',
      'Tmn Teratai Mewah',
      'Tmn Wangsa Melawati',
      'Wangsa Maju',
    ],
  },
  'Selangor': {
    'Gombak': [
      'Ampang',
      'Batu Caves',
      'Gombak',
      'Hulu Klang',
      'Kuang',
      'Rawang',
      'Selayang',
      'Setapak',
    ],
    'Hulu Langat': [
      'Ampang',
      'Beranang',
      'Cheras',
      'Hulu Langat',
      'Hulu Semenyih',
      'Kajang',
      'Semenyih',
    ],
    'Hulu Selangor': [
      'Ampang Pecah',
      'Batang Kali',
      'Bulur Telur',
      'Hulu Bernam',
      'Hulu Yam',
      'Kalumpang',
      'Kerling',
      'Kuala Kalumpang',
      'Peretak',
      'Rasa',
      'Serendah',
      'Sg Gamut',
      'Sg Tinggi',
    ],
    'Klang': [
      'Kapar',
      'Klang',
    ],
    'Kuala Langat': [
      'Bandar',
      'Batu',
      'Jugra',
      'Kelanang',
      'Morib',
      'Tanjung 12',
      'Teluk Panglima Garang',
    ],
    'Kuala Selangor': [
      'Api-Api',
      'Bestari Jaya',
      'Hulu Tinggi',
      'Ijok',
      'Jeram',
      'Kuala Selangor',
      'Pasangan',
      'Tanjung Karang',
      'Ujong Permatang',
    ],
    'Petaling': [
      'Bkt Raja',
      'Damansara',
      'Petaling',
      'Petaling Jaya',
      'Puchong',
      'Seri Kembangan',
      'Sg Buloh',
      'Shah Alam',
      'Subang',
      'Subang Jaya',
    ],
    'Sabak Bernam': [
      'Bagan Nakhoda Omar',
      'Panchang Bedena',
      'Pasir Panjang',
      'Sabak',
      'Sg Panjang',
    ],
    'Sepang': [
      'Cyberjaya',
      'Dengkil',
      'Labu',
      'Salak Tinggi',
      'Sepang',
    ],
  },
  'N.Sembilan': {
    // 'Jelebu': [],
    // 'Jempol': [],
    // 'Kuala Pilah': [],
    'Nilai': [
      'Bdr Baru Nilai',
      'Bdr Enstek',
      'Bdr Seremban Selatan',
      'Labu',
      'Lenggeng',
      'Mantin',
      'Nilai',
      'Pajam',
      'Pantai',
      'Rantau',
      'Rasah Kemayan',
      'Sg Gadut',
      'Tmn Seremban Jaya',
      'Tmn Tuanku Jaafar',
      'Ulu Beranang',
    ],
    // 'Port Dickson': [],
    // 'Rembau': [],
    'Seremban': [
      'Ampangan',
      'Bdr Sri Sendayan',
      'Bkt Blossom',
      'Bkt Chedang',
      'Bkt Kepayang',
      'Kemayan',
      'Lobak',
      'Mambau',
      'Oakland',
      'Paroi',
      'Rahang',
      'Rasah',
      'Rasah Jaya',
      'Senawang',
      'Seremban',
      'Seremban 2',
      'Sikamat',
      'Temiang',
      'Tmn Permai',
    ],
    // 'Tampin': [],
  },
};
